apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      # (old value) image: stephengrider/multi-client
      image: stephengrider/multi-worker
      ports:
        # - containerPort: 9999  >>>  error! Only some fields can be updated (not this, for example!)
        - containerPort: 3000

# minikube start
# kubectl apply -f client-pod.yaml
# kubectl get pods
# kubectl describe <object-type> <object-name>
#   kubectl describe pod client-pod
