# object not defined in k8s
# defined in cert-manager installed with helm!

# ISSUER = object describing details about the certificate that should be obtainer

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

  # base address which the certificate is valid for
  commonName: k8s-multi.com

  # different domains associated to the certificate
  dnsNames:
    - k8s-multi.com
    - www.k8s-multi.com

  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s-multi.com
          - www.k8s-multi.com