# object not defined in k8s
# defined in cert-manager installed with helm!

# ISSUER = object telling cert-manager where to get the certificate from

apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'giacomoweb@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
